"""The frame format spoken between the in-process agent and the control process.

The layout is fixed in `docs/system/02-interface.md`. Anything changed here has to be changed in `agent/Wire.java` as well, and the protocol version has to be raised so a mismatched pair refuses to talk rather than misreading each other.
"""

from .frames import (
    Frame,
    HEADER_SIZE,
    Kind,
    PROTOCOL_VERSION,
    decode_header,
    encode,
    read_frame,
)
from .observation import (
    BLOCK_EVENTS,
    BLOCK_REGIONS,
    BLOCK_SQUADS,
    BLOCK_UNITS,
    EventState,
    BUILT,
    NO_ORDER,
    NO_SQUAD,
    NO_TARGET,
    Observation,
    REGION_SLOTS,
    RegionState,
    SQUAD_SLOTS,
    SquadState,
    UnitState,
    decode_observation,
)
from .action import (
    Action,
    Commander,
    Contract,
    Deviation,
    Production,
    ProductionKind,
    SquadAssignment,
    SquadDeviation,
    Stance,
    Status,
    Task,
    encode_action,
)

__all__ = [
    "BLOCK_EVENTS",
    "BLOCK_REGIONS",
    "BLOCK_SQUADS",
    "BLOCK_UNITS",
    "BUILT",
    "NO_ORDER",
    "NO_SQUAD",
    "NO_TARGET",
    "Action",
    "Commander",
    "Contract",
    "Deviation",
    "EventState",
    "Frame",
    "HEADER_SIZE",
    "Kind",
    "Observation",
    "PROTOCOL_VERSION",
    "Production",
    "ProductionKind",
    "REGION_SLOTS",
    "RegionState",
    "SQUAD_SLOTS",
    "SquadAssignment",
    "SquadDeviation",
    "SquadState",
    "Stance",
    "Status",
    "Task",
    "UnitState",
    "decode_header",
    "decode_observation",
    "encode",
    "encode_action",
    "read_frame",
]
